(() => {
  const texts = {
    pt: {
      heroTitle: "Sessao guiada",
      heroSubtitle: "Painel ao vivo da extensao",
      statusHeading: "Status da sessao",
      statusSub: "Acompanhe a fase atual do bot",
      progressHeading: "Progresso",
      progressSub: "A fase atual aparece em tempo real",
      configHeading: "Configuracao",
      configSub: "Idioma primeiro, depois a janela de busca, as automacoes e os ajustes avancados",
      configHint: "Idioma, janela de busca, automacoes e ajustes avancados estao separados abaixo.",
      controlTitle: "Controle no painel lateral",
      controlBody: "Use o botao da barra lateral da pagina para iniciar ou parar o bot.",
      sessionScope: "por sessao",
      configScope: "salvar",
      missingDateTitle: "Informe a data minima e a marcada",
      missingDateBody: "A data minima e o piso da busca; a data marcada e a data mais recente ja reservada no site.",
      sessionSummaryDefault: "Aguardando dados da extensao.",
      liveNoUpdate: "Sem atualizacao ainda",
      statusReady: "Pronto",
      statusDisabled: "Desativado",
      labelLocation: "Localizacao",
      labelSelectedDate: "Data ja marcada",
      labelMinimumDate: "Data minima da busca",
      labelSearchLimit: "Limite da busca",
      labelMonth: "Mes em foco",
      labelDay: "Dia em foco",
      labelTime: "Horario",
      searchHintNoDate: "Defina a data minima da busca e a data ja marcada abaixo para deixar o limite da busca visivel.",
      searchHintWithDate: "A busca antes de {selected} usa {limit} como limite.",
      searchHintWithRange: "A busca fica entre {minimum} e {limit}.",
      configHintNoDate: "Exemplo: preencha a data minima da busca e a data ja marcada para limitar a busca.",
      configHintWithDate: "Exemplo: {selected} -> {limit}.",
      configHintWithRange: "Exemplo: {minimum} -> {selected} -> {limit}.",
      enabledLabel: "Bot ativo",
      delayLocationLabel: "Atraso da localizacao (ms)",
      delayCalendarLabel: "Atraso do calendario (ms)",
      delayBackLabel: "Atraso do retorno (ms)",
      selectedDateConfigLabel: "Data ja marcada",
      minimumDateConfigLabel: "Data minima da busca",
      languageLabel: "Idioma",
      languageSectionTitle: "Idioma",
      languageSectionSub: "Escolha o idioma do assistente antes de salvar a configuracao.",
      languageHelp: "Este idioma tambem define o texto do assistente inicial.",
      dateWindowTitle: "Janela de busca",
      dateWindowSub: "A data minima e o piso. A data marcada e a ultima reserva feita no site.",
      minimumDateHelp: "Primeira data que o bot pode considerar.",
      selectedDateHelp: "Data mais recente ja reservada no site. O bot busca ate o dia anterior.",
      autoSelectTimeLabel: "Selecionar horario automaticamente",
      autoSelectTimeHelp: "Quando desligado, voce escolhe o horario manualmente na pagina.",
      autoContinueReviewLabel: "Continuar automaticamente na revisao",
      autoContinueReviewHelp: "Quando desligado, voce confirma a pagina de revisao manualmente.",
      autoFinishAppointmentLabel: "Finalizar automaticamente",
      autoFinishAppointmentHelp: "Quando desligado, voce clica em Finish manualmente na pagina final.",
      automationSectionTitle: "Automacoes",
      automationSectionSub: "Defina o que o bot faz sozinho depois de achar uma data.",
      advancedSectionTitle: "Avancado",
      advancedSectionSub: "Ajuste os atrasos do fluxo se quiser mais paciencia entre as etapas.",
      toggleBotOn: "Iniciar bot",
      toggleBotOff: "Parar bot",
      updateDateButton: "Atualizar data",
      saveButton: "Salvar alteracoes",
      savedButton: "Salvo!",
      optionPt: "Portugues",
      optionEn: "Ingles",
      optionEs: "Espanhol",
      phaseReady: "Pronto",
      phaseDisabled: "Desativado",
      phaseLoading: "Carregando dados",
      phaseLocation: "Selecionando localizacao",
      phaseLocationSelected: "Localizacao selecionada",
      phaseCalendar: "Verificando calendario",
      phaseCalendarReady: "Calendario pronto",
      phaseTime: "Selecionando horario",
      phaseTimeManual: "Horario manual",
      phaseTimeSelected: "Horario selecionado",
      phaseReview: "Revisando confirmacao",
      phaseReviewManual: "Revisao manual",
      phaseFinish: "Finalizando agendamento",
      phaseFinishManual: "Aguardando Finish",
      phasePaused: "Pausado",
      phaseRefresh: "Atualizando busca",
      phaseDone: "Concluido",
      stageLocation: "Localizacao",
      stageCalendar: "Calendario",
      stageTime: "Horario",
      stageWaitingLocation: "Dublin Burgh Quay",
      stageWaitingCalendar: "Aguardando o calendario",
      stageWaitingTime: "Aguardando horario",
      stageWaitingTimeManual: "Escolha o horario manualmente",
      stageCalendarDetail: "Verificando {month}{limit}",
      stageTimeDetail: "Aguardando horario",
      liveUpdated: "Atualizado {time}",
      checkpointSession: "Sessao",
      checkpointWaiting: "Aguardando checkpoints"
    },
    en: {
      heroTitle: "Guided session",
      heroSubtitle: "Live extension dashboard",
      statusHeading: "Session status",
      statusSub: "Track the bot's current stage",
      progressHeading: "Progress",
      progressSub: "The current stage updates in real time",
      configHeading: "Settings",
      configSub: "Language first, then the search window, automations, and advanced timing",
      configHint: "Language, search window, automations, and advanced timing are split below.",
      controlTitle: "Control in the side panel",
      controlBody: "Use the button in the page side panel to start or stop the bot.",
      sessionScope: "per session",
      configScope: "save",
      missingDateTitle: "Enter the minimum and booked dates",
      missingDateBody: "The minimum date is the search floor; the booked date is the most recent date already saved on the site.",
      sessionSummaryDefault: "Waiting for data from the extension.",
      liveNoUpdate: "No update yet",
      statusReady: "Ready",
      statusDisabled: "Disabled",
      labelLocation: "Location",
      labelSelectedDate: "Booked date",
      labelMinimumDate: "Search minimum date",
      labelSearchLimit: "Search limit",
      labelMonth: "Active month",
      labelDay: "Active day",
      labelTime: "Time",
      searchHintNoDate: "Set the search minimum date and the booked date below to make the search limit visible.",
      searchHintWithDate: "Searching before {selected} uses {limit} as the limit.",
      searchHintWithRange: "Search stays between {minimum} and {limit}.",
      configHintNoDate: "Example: fill the search minimum date and the booked date to limit the search.",
      configHintWithDate: "Example: {selected} -> {limit}.",
      configHintWithRange: "Example: {minimum} -> {selected} -> {limit}.",
      enabledLabel: "Bot active",
      delayLocationLabel: "Location delay (ms)",
      delayCalendarLabel: "Calendar delay (ms)",
      delayBackLabel: "Back delay (ms)",
      selectedDateConfigLabel: "Booked date",
      minimumDateConfigLabel: "Search minimum date",
      languageLabel: "Language",
      languageSectionTitle: "Language",
      languageSectionSub: "Choose the assistant language before saving the rest.",
      languageHelp: "This also controls the setup wizard copy.",
      dateWindowTitle: "Search window",
      dateWindowSub: "Minimum date is the floor. Booked date is the last reservation already on the site.",
      minimumDateHelp: "First date the bot can consider.",
      selectedDateHelp: "Most recent date already booked on the site. The bot searches up to the day before.",
      autoSelectTimeLabel: "Automatically select time",
      autoSelectTimeHelp: "When off, you choose the time manually on the page.",
      autoContinueReviewLabel: "Automatically continue on review",
      autoContinueReviewHelp: "When off, you confirm the review page manually.",
      autoFinishAppointmentLabel: "Automatically finish",
      autoFinishAppointmentHelp: "When off, you click Finish manually on the final page.",
      automationSectionTitle: "Automations",
      automationSectionSub: "Choose what the bot does by itself after it finds a date.",
      advancedSectionTitle: "Advanced",
      advancedSectionSub: "Adjust the flow delays if you want more patience between steps.",
      toggleBotOn: "Start bot",
      toggleBotOff: "Stop bot",
      updateDateButton: "Update date",
      saveButton: "Save changes",
      savedButton: "Saved!",
      optionPt: "Portuguese",
      optionEn: "English",
      optionEs: "Spanish",
      phaseReady: "Ready",
      phaseDisabled: "Disabled",
      phaseLoading: "Loading data",
      phaseLocation: "Selecting location",
      phaseLocationSelected: "Location selected",
      phaseCalendar: "Checking calendar",
      phaseCalendarReady: "Calendar ready",
      phaseTime: "Selecting time",
      phaseTimeManual: "Manual time",
      phaseTimeSelected: "Time selected",
      phaseReview: "Reviewing confirmation",
      phaseReviewManual: "Manual review",
      phaseFinish: "Finishing appointment",
      phaseFinishManual: "Waiting for Finish",
      phasePaused: "Paused",
      phaseRefresh: "Refreshing search",
      phaseDone: "Done",
      stageLocation: "Location",
      stageCalendar: "Calendar",
      stageTime: "Time",
      stageWaitingLocation: "Dublin Burgh Quay",
      stageWaitingCalendar: "Waiting for the calendar",
      stageWaitingTime: "Waiting for time",
      stageWaitingTimeManual: "Choose the time manually",
      stageCalendarDetail: "Checking {month}{limit}",
      stageTimeDetail: "Waiting for time",
      liveUpdated: "Updated {time}",
      checkpointSession: "Session",
      checkpointWaiting: "Waiting for checkpoints"
    },
    es: {
      heroTitle: "Sesion guiada",
      heroSubtitle: "Panel en vivo de la extension",
      statusHeading: "Estado de la sesion",
      statusSub: "Sigue la fase actual del bot",
      progressHeading: "Progreso",
      progressSub: "La fase actual se actualiza en tiempo real",
      configHeading: "Configuracion",
      configSub: "Idioma primero, luego la ventana de busqueda, las automatizaciones y los ajustes avanzados",
      configHint: "Idioma, ventana de busqueda, automatizaciones y ajustes avanzados van separados abajo.",
      controlTitle: "Control en el panel lateral",
      controlBody: "Usa el boton del panel lateral de la pagina para iniciar o detener el bot.",
      sessionScope: "por sesion",
      configScope: "guardar",
      missingDateTitle: "Ingresa la fecha minima y la reservada",
      missingDateBody: "La fecha minima es el piso de busqueda; la fecha reservada es la mas reciente ya guardada en el sitio.",
      sessionSummaryDefault: "Esperando datos de la extension.",
      liveNoUpdate: "Sin actualizacion aun",
      statusReady: "Listo",
      statusDisabled: "Desactivado",
      labelLocation: "Ubicacion",
      labelSelectedDate: "Fecha reservada",
      labelMinimumDate: "Fecha minima de busqueda",
      labelSearchLimit: "Limite de busqueda",
      labelMonth: "Mes activo",
      labelDay: "Dia activo",
      labelTime: "Horario",
      searchHintNoDate: "Define la fecha minima de busqueda y la fecha reservada abajo para mostrar el limite de busqueda.",
      searchHintWithDate: "Buscar antes de {selected} usa {limit} como limite.",
      searchHintWithRange: "La busqueda queda entre {minimum} y {limit}.",
      configHintNoDate: "Ejemplo: completa la fecha minima de busqueda y la fecha reservada para limitar la busqueda.",
      configHintWithDate: "Ejemplo: {selected} -> {limit}.",
      configHintWithRange: "Ejemplo: {minimum} -> {selected} -> {limit}.",
      enabledLabel: "Bot activo",
      delayLocationLabel: "Retardo de ubicacion (ms)",
      delayCalendarLabel: "Retardo del calendario (ms)",
      delayBackLabel: "Retardo de volver (ms)",
      selectedDateConfigLabel: "Fecha reservada",
      minimumDateConfigLabel: "Fecha minima de busqueda",
      languageLabel: "Idioma",
      languageSectionTitle: "Idioma",
      languageSectionSub: "Elige el idioma del asistente antes de guardar lo demas.",
      languageHelp: "Esto tambien cambia el texto del asistente inicial.",
      dateWindowTitle: "Ventana de busqueda",
      dateWindowSub: "La fecha minima es el piso. La reservada es la ultima reserva ya hecha en el sitio.",
      minimumDateHelp: "Primera fecha que el bot puede considerar.",
      selectedDateHelp: "Fecha mas reciente ya reservada en el sitio. El bot busca hasta el dia anterior.",
      autoSelectTimeLabel: "Seleccionar horario automaticamente",
      autoSelectTimeHelp: "Cuando esta apagado, eliges el horario manualmente en la pagina.",
      autoContinueReviewLabel: "Continuar automaticamente en revision",
      autoContinueReviewHelp: "Cuando esta apagado, confirmas la pagina de revision manualmente.",
      autoFinishAppointmentLabel: "Finalizar automaticamente",
      autoFinishAppointmentHelp: "Cuando esta apagado, haces clic en Finish manualmente en la pagina final.",
      automationSectionTitle: "Automatizaciones",
      automationSectionSub: "Elige lo que el bot hace por si solo despues de encontrar una fecha.",
      advancedSectionTitle: "Avanzado",
      advancedSectionSub: "Ajusta los retrasos del flujo si quieres mas paciencia entre pasos.",
      toggleBotOn: "Iniciar bot",
      toggleBotOff: "Detener bot",
      updateDateButton: "Actualizar fecha",
      saveButton: "Guardar cambios",
      savedButton: "Guardado!",
      optionPt: "Portugues",
      optionEn: "Ingles",
      optionEs: "Espanol",
      phaseReady: "Listo",
      phaseDisabled: "Desactivado",
      phaseLoading: "Cargando datos",
      phaseLocation: "Seleccionando ubicacion",
      phaseLocationSelected: "Ubicacion seleccionada",
      phaseCalendar: "Verificando calendario",
      phaseCalendarReady: "Calendario listo",
      phaseTime: "Seleccionando horario",
      phaseTimeManual: "Horario manual",
      phaseTimeSelected: "Horario seleccionado",
      phaseReview: "Revisando confirmacion",
      phaseReviewManual: "Revision manual",
      phaseFinish: "Finalizando cita",
      phaseFinishManual: "Esperando Finish",
      phasePaused: "Pausado",
      phaseRefresh: "Actualizando busqueda",
      phaseDone: "Completado",
      stageLocation: "Ubicacion",
      stageCalendar: "Calendario",
      stageTime: "Horario",
      stageWaitingLocation: "Dublin Burgh Quay",
      stageWaitingCalendar: "Esperando el calendario",
      stageWaitingTime: "Esperando horario",
      stageWaitingTimeManual: "Elige el horario manualmente",
      stageCalendarDetail: "Verificando {month}{limit}",
      stageTimeDetail: "Esperando horario",
      liveUpdated: "Actualizado {time}",
      checkpointSession: "Sesion",
      checkpointWaiting: "Esperando checkpoints"
    }
  };

  globalThis.IRPPopupTexts = Object.freeze(texts);
})();
